version: '3.8'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    stdin_open: true
    restart: always
    ports:
      - 4000:80
  client:
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    restart: always
    ports:
      - 3000:3000
    volumes:
      - './client/src:/app/src'
      - './client/public:/app/public'
